language: node_js
node_js:
  - 8
  - 9
  - 10

after_success:
  - npm run build-storybook  

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: storybook-migration

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: storybook-static
  on:
    branch: storybook-migration