language: node_js
node_js:
  - 8

after_success:
  - npm install
  - npm run build-storybook  

deploy:
- provider: script
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  script: npm publish
  on:
    branch: storybook-migration
- provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: storybook-static
  on:
    branch: storybook-migration